### ISSUE TITLE
Using nested classes for saga data results in incorrect azure table storage table name fo

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.Persistence.AzureStorage#100]
Imagine having the the following sagas:

``` c#
public class MyFirstCoolSaga
{
    public class Data : ContainSagaData
    {
        public long Id { get; set; }
    }
}

public class MySecondEvenCoolerSata
{
    public class Data : ContainSagaData
    {
        public long Id { get; set; }
    }
}
```

Both saga data classes will now store their data in `Data`. This can result in issues.

Comparing this to NHibernate, NHibernate uses the name from the parent/outer class. The sagas seen in the following image use the same construction as the above mentioned snippet.
# Proposal
1. Use the same behavior as NHibernate, use the outer class name
2. Use the outer class name and the nested class name
3. User the full type name (namespace + outer + nested names)
# References
- This issue was found while implementing https://github.com/Particular/EndToEnd/issues/198

**Comment by Scooletz** [comment]
We agreed on the following the only issue it can result is the data management perspective that one can't access all sagas of a specific type. This could be helpful when obsoleting an endpoint and trying to remove all the sagas of a specific type. With this current approach, one would need to filter out this data. With an approach taking into consideration parent's name, instead of filtering a whole table could be dropped.

@Particular/azure-storage-persistence-maintainers Please chime in.

**Comment by weralabaj** [comment]
@Scooletz we have a similar issue in Raven, in your case the saga data won't be overwritten if two different sagas will to save it? in NHibernate if the saga data is a nested class, they use saga class name to identify data, how do you do it?

**Comment by Scooletz** [comment]
In Azure Storage Persister we use following algorithm for creating the secondary index key:

```
var sagaDataTypeName = sagaType.FullName;
var key = $"Index_{sagaDataTypeName}_{correlationProperty.Name}_{Serialize(correlationProperty.Value)}";
```
There's event [a test for it](https://github.com/Particular/NServiceBus.Persistence.AzureStorage/blob/develop/src/NServiceBus.Persistence.AzureStorage.ComponentTests/Sagas/SecondaryIndexKeyBuilderTests.cs#L13-L21).

Although entries for both types are stored in the same table, I see no "issues" with it as the secondary index is based on the full type name and sagas are stored by their GUID id.

Could you clarify what kind of issues it may result with @ramonsmits ?

**Comment by ramonsmits** [comment]
Its not about the index. Its about different saga entities being stored in the same Azure Storage Table if I remember correctly. You would not expect this, you would expect each entity type to be stored in their own table.

**Comment by Scooletz** [comment]
Why would you not expect this? If you take the first look at the tables and see that they are based on the `IContainSagaData` implementing class name, this is clear that tables are named after the class.
I'm sorry but still don't see any reason for being confused. @Particular/azure-maintainers ?

**Comment by ramonsmits** [comment]
@Scooletz as this is not aligned with the behavior I'm used to that I got with NHibernate. :-)

It is just a proposal, it is up to you to ignore it.

**Comment by Scooletz** [comment]
I see your point now. Thank you for clarifying. I'm closing it though as it has no impact on performance nor on the correctness of the library. Additionally, when searching for a saga by its id, one would still look to the correctly name table.
