### ISSUE TITLE
Subscriptions are not updated

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus.Persistence.AzureStorage#101]
When a new subscription arrives for an endpoint already having a subscription persisted, the new subscription is discarded. With v6, the new subscription contains additional information about the logical endpoint, required for sender-side distribution which is then not available. This will lead to duplicate events dispatched to scaled out instances.

Failing test available here: https://github.com/Particular/NServiceBus.Persistence.AzureStorage/commit/cecde17ef218817816cc5ac2ee58b6147a5774a0

ping @Particular/azure-storage-persistence-maintainers

**Comment by Scooletz** [comment]
Cool. I'm on it.

**Comment by timbussmann** [comment]
@Scooletz :+1:  ! (I think this needs to be included in the final release)

**Comment by Scooletz** [comment]
The PR has been merged. Should I mark with the milestone now @timbussmann ?

**Comment by timbussmann** [comment]
> The PR has been merged. Should I mark with the milestone now @timbussmann ?

If it's already in, no need to I think. We used that milestone as a tracker for items left to do (in case we don't want them to be on the generated release notes). Can you link the PR to this issue if you already fixed it?

**Comment by Scooletz** [comment]
Sure. I'm closing this.
