### ISSUE TITLE
Microsoft.WindowsAzure.Storage v7.2.1.0 not recognized

### ISSUE THREAD

**Issue by robbihun** [Particular/NServiceBus.Persistence.AzureStorage#113]
I'm not sure where to post this, but decided on this repo as it seems to be the package that is compiled with an older version of Microsoft.WindowsAzure.Storage (v7.0.0.0).

In a new project i'm setting up in order to migrate from ravendb and msmq, using NServiceBus.Host  version 7.0.0 and NServiceBus version 6.0.0 - I have it configured to use AzureDataBus and AzureStoragePersistence; however, AzureDataBus requires Microsoft.WindowsAzure.Storage v7.2.0 or greater (so i have 7.2.1 installed). I added a binding redirect to my app.config and also created an NServiceBust.Host.exe.Config with the same binding redirect; however, when i debug my application it always fails trying to load Microsoft.WindowsAzure.Storage v7.0.0.0 for AzureStoragePersistence and the binding redirect seems to be insufficient or ignored. I noticed in the [sample repository for AzureStoragePersistence](https://github.com/Particular/docs.particular.net/blob/master/samples/azure/storage-persistence/ASP_1/Server/app.config) they're using a binding redirect for Microsoft.WindowsAzure.Storage with the same version so it should work. I'm not sure why i'm receiving this error or the next steps to troubleshoot to help pin it down.

My app.config binding redirects

``` xml
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Data.Edm" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.7.0.0" newVersion="5.7.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Data.Services.Client" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.7.0.0" newVersion="5.7.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Data.OData" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.7.0.0" newVersion="5.7.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="NServiceBus.Core" publicKeyToken="9fc386479f8a226c" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-6.0.0.0" newVersion="6.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.WindowsAzure.Storage" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-7.2.1.0" newVersion="7.2.1.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
```

My NServicebus EndpointConfiguration Customize Method:

``` csharp
        public void Customize(EndpointConfiguration configuration)
        {
            configuration.UseTransport<AzureServiceBusTransport>()
                .UseTopology<ForwardingTopology>();

            // Not compatible with Microsoft.WindowsAzure.Storage v7.0.0, requires 7.2.0 or greater.
            configuration.UseDataBus<AzureDataBus>()
                .ConnectionString(ConfigurationManager.ConnectionStrings["AzureBlobStorage"].ConnectionString);

            // Doesnt seem compatible with Microsoft.WindowsAzure.Storage v7.2.0 or 7.2.1, i cant get it to work even with a binding redirect
            // I may have to continue using Raven until this is resolved.
            configuration.UsePersistence<AzureStoragePersistence>()
                .ConnectionString(ConfigurationManager.ConnectionStrings["AzureBlobStorage"].ConnectionString);

            // Work with this, not with AzureStoragePersistence
            //configuration.UsePersistence<RavenDBPersistence>();

            configuration.UseSerialization<JsonSerializer>();

            configuration.EnableInstallers();
        }
```

The exception i get when running this:

```
{"Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information."}

{"Could not load file or assembly 'Microsoft.WindowsAzure.Storage, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)":"Microsoft.WindowsAzure.Storage, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"}
```

And the output from NServiceBus.Host.exe

![image](https://cloud.githubusercontent.com/assets/138997/19359952/01e96f4e-9142-11e6-8596-7367b8b1b1bf.png)

**Comment by robbihun** [comment]
Just to add... maybe this is an issue with NServiceBus.Host? I just cloned the sample repository I referenced above and added azureservicebustransport and azuredatabus and it seems to work fine. But, when i convert the "server" project to use nservicebus.host i get the same results... So, easy steps to reproduce:

1. [Clone this project](https://github.com/Particular/docs.particular.net/tree/master/samples/azure/storage-persistence/ASP_1)
1. Install the following nuget packages
  1. NServiceBus.Azure.Transports.WindowsAzureServiceBus -Version 7.0.1
  1. NServiceBus.DataBus.AzureBlobStorage -Version 1.0.0
1. Add the following to program.cs (as appropriate)
```
	var transport = endpointConfiguration.UseTransport<AzureServiceBusTransport>();
	transport.ConnectionString("{redacted}");
	transport.UseTopology<ForwardingTopology>();

	var persistence = endpointConfiguration.UsePersistence<AzureStoragePersistence>();
	persistence.ConnectionString("UseDevelopmentStorage=true");

	var databus = endpointConfiguration.UseDataBus<AzureDataBus>();
	databus.ConnectionString("UseDevelopmentStorage=true");
```

At this point running the program should work as expected.

Now, add NServiceBus.Host -Version 7.0.0.0 and copy the configuration from the program.cs into the endpointconfig that was generated from the nuget install. Delete program.cs and run your program, you should hit this issue.

**Comment by robbihun** [comment]
Okay, last comment and i think i've figured it out...

In the sample project adding the binding redirects to NServiceBus.Host.exe.config worked so i tried that again in my project and it is working - perhaps i fat-fingered "NServiceBus.Host.exe.config" previously.

Still would like to document this here so it can help others if needed.

**Comment by SeanFeldman** [comment]
@Particular/azure-storage-persistence-maintainers an issue for docs?

**Comment by Scooletz** [comment]
I'm reopenning it just for sake of visibility. As soon as we have an outcome we'll close it.

**Comment by SimonCropp** [comment]
@SeanFeldman @Scooletz i think this is already covered in doco https://docs.particular.net/nservicebus/hosting/nservicebus-host/#application-domains

**Comment by SeanFeldman** [comment]
Agreed. I'm 👍 to close.
