### ISSUE TITLE
Table storage saga persister doesn't support nullables

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus.Persistence.AzureStorage#115]
Nullables are supported by azure table storage

```
  [Test]
        public async Task ShouldHandleNullableDoubles()
        {
            var id = Guid.NewGuid().ToString();

            await Storage.Store(new EntityWithNullableDouble
            {
                RowKey = id,
                PartitionKey = id
            });

            var loadedWithNull = await Storage.Load<EntityWithNullableDouble>(id);

            Assert.False(loadedWithNull.SomeDouble.HasValue);

            var value = 6.4;
            loadedWithNull.SomeDouble = value;

            await Storage.Update(loadedWithNull);

            var loadedWithNonNull = await Storage.Load<EntityWithNullableDouble>(id);


            Assert.True(loadedWithNonNull.SomeDouble.HasValue);

            Assert.AreEqual(value, loadedWithNonNull.SomeDouble.Value);
        }
```

But the persister doesn't allow it:

https://github.com/Particular/NServiceBus.Persistence.AzureStorage/blob/develop/src/NServiceBus.Persistence.AzureStorage/SagaPersisters/DictionaryTableEntityExtensions.cs#L112

**Comment by SeanFeldman** [comment]
Looks like a [bug](https://github.com/Azure/azure-sdk-for-net/issues/137) from a far past (client v2) that got fixed, but ASP code never updated.

**Comment by SeanFeldman** [comment]
Ironically, [official doco](https://msdn.microsoft.com/library/azure/dd179338.aspx#Tables, Entities, and Properties) is still not updated

**Comment by Scooletz** [comment]
I can handle this under `maintainer budget`
