### ISSUE TITLE
DevOps concerns for Azure Persistence

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.Persistence.AzureStorage#124]
Simon Cropp [17:49]  
@azure-maintainers re the azure storage  persister 
I think we need to take the persistence doco to the next level.

I want to focus on the DevOps are to fit with the new wave

There are a number of "DevOps areas" that i think our persistence doco/features are lacking.

* Changing the correlation property type
* moving to a different property for correlation
* Splitting Sagas
* Merging Sagas
* Renaming Sagas
* Renaming a Saga Property
* Possibly something i have not though of

For comparison have a look at https://docs.particular.net/samples/serializers/transitioning-formats/

For each of the above we have two options

* A Hot update (no downtime or migration required)
* A migration. ie stop all endpoints, run some script, start all endpoints

Obviously Hot is preferred in most cases.

Note that for hot updates it may be necessary to have query functionality documented/implemented.
For example if i have "hot" migration code that upgrades a Saga when it is touched i will need to be able to run a query to know when all are migrated so i can remove the migration code.

Each may require

* Only documentation
* Changes to the persister. Might be small enough to do under maintainer budget or perhaps need to be escalated to PlatDev
* Changes to the core persistence seem

So what do you think? are these things that the maintainer group can own and push forward?

Connects to Connects to https://github.com/Particular/NServiceBus.Azure/issues/310

**Comment by SimonCropp** [comment]
so this issue has got no love for a while now. there is a lot of value we can deliver to users in an incremental that easily fits within the maintainer budget. Also much of this value can be delivered in the best possible way, ie no need to write deployed code and do a release.

**Comment by tmasternak** [comment]
@SimonCropp we will groom this on Monday and let you know the outcome.

**Comment by Scooletz** [comment]
@SimonCropp We're not done with grooming the current backlog. Once we're done (~2 weeks) we'll prioritize this and update the issue.

**Comment by danielmarbach** [comment]
Closing this for now since we don't have anything planed to follow up with this

**Comment by Scooletz** [comment]
I'm fine with it @danielmarbach 👍
