### ISSUE TITLE
Create a one time upgrade script to create missing saga secondary index records

### ISSUE THREAD

**Issue by boblangley** [Particular/NServiceBus.Persistence.AzureStorage#132]
In order to eliminate full table scans for saga access secondary index records are required for each saga. Endpoints upgrade to >= 6.2.4 support secondary index records, but only create them on-demand at runtime. Creating a script would allow a users to generate any missing secondary index records eliminating the need for full table scans.

To avoid full table scans when creating a new saga, we will require a mechanism for the user to indicate that this upgrade has been performed so the persistence can skip full table scans.

**Comment by SeanFeldman** [comment]
Will be required for v1 and backported to support-6.2

**Comment by SeanFeldman** [comment]
@tekmaven raised this as an issue in #130. @Particular/azure-maintainers we should assign this a milestone.

**Comment by SeanFeldman** [comment]
Closing in favor of #130

**Comment by SeanFeldman** [comment]
Reopening. Will need to be reviewed after `2.0.0` is out.

**Comment by SeanFeldman** [comment]
The context is lost and all of the customers at this point no longer require it.
