### ISSUE TITLE
Release 1.1

### ISSUE THREAD

**Issue by Scooletz** [Particular/NServiceBus.Persistence.AzureStorage#135]
PoA:
- [x] Bump up the storage library to 8.* https://www.nuget.org/packages/WindowsAzure.Storage/
- [x] mark PRs/issues with the milestone
- [x] create `release-1.1`
- [x] release RC to myget
- [x] smoke test 
- [x] merge to master and release to myget
- [x] bump up docs (https://github.com/Particular/docs.particular.net/pull/2504)
- [x] ~prepare `hotfix-1.1.1` widening the nuspec range~
- [x] prepare `release-1.2` lowering dependencies of the storage library
- [x] release in cohort with other Azure libs (`1.2` first, then `1.1`)
- [x] release an announcement that informs about 1.1 and 1.2 in one message

See https://github.com/Particular/NServiceBus.AzureStorageQueues/issues/187 for cohort release

**Comment by SeanFeldman** [comment]
Need `support-1.0` branch

**Comment by SeanFeldman** [comment]
Released
