### ISSUE TITLE
Remove nuget package dependency on Newtonsoft.JSON

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus.Persistence.AzureStorage#149]
Connects to https://github.com/Particular/NServiceBus.Azure/issues/300

To avoid version conflicts with other libraries that use json.net, it would be better if we didn't

**Comment by Scooletz** [comment]
@danielmarbach 's comment can be applied in here as well https://github.com/Particular/NServiceBus.Persistence.ServiceFabric/issues/36#issuecomment-312004451
