### ISSUE TITLE
Upgrading a core 5 publisher to core 6 results in duplicate subscriptions when the subscriber auto subscribes after its restart.

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.Persistence.AzureStorage#154]
Upgrading a core 5 publisher to core 6 results in duplicate subscriptions when the subscriber auto subscribes after its restart. When the publisher published the event the (core 5) subscriber now receives this event twice which is not expected.

## CSV Export of subscriptions

```csv
PartitionKey,RowKey,Timestamp,EndpointName:System.String
OrderCompleted, Version=0.0.0.0,U2FtcGxlcy5BenVyZS5TdG9yYWdlUGVyc2lzdGVuY2UuQ2xpZW50,21-7-2017 14:57:09,"Samples.Azure.StoragePersistence.Client"
OrderCompleted, Version=0.0.0.0,U2FtcGxlcy5BenVyZS5TdG9yYWdlUGVyc2lzdGVuY2UuQ2xpZW50QFVzZURldmVsb3BtZW50U3RvcmFnZT10cnVl,21-7-2017 14:54:03,null
```

**Comment by ramonsmits** [comment]
Any updates on this? This seems like a bug to me.

**Comment by SeanFeldman** [comment]
I'll be working on this today @ramonsmits

**Comment by SeanFeldman** [comment]
@ramonsmits this doesn't look right.
Looking at the subscription data, you've got something skewing your test.
When upgrading from version 5 to version 6 of NServiceBus, your subscription info doesn't change. You can use [this sample](https://docs.particular.net/samples/azure/storage-persistence/) to verify it (has both v5 and v6 samples).

Looking at what you've posted, you've got different endpoints (values in RowKey):
`Samples.Azure.StoragePersistence.Client`
vs
`Samples.Azure.StoragePersistence.Client@UseDevelopmentStorage=true`

Please re-open if you find something that should be actioned. Thank you.

**Comment by ramonsmits** [comment]
@SeanFeldman That is the sample that I used. I used https://docs.particular.net/samples/azure/storage-persistence/?version=azure_6 and https://docs.particular.net/samples/azure/storage-persistence/

And yes, I'm was using development storage. 

Problem with that sample is that it is using the learning transport which supports pubsub so will not use the subscription storage.

This is my modified sample that uses Azure Storage Queues as the transport:

- https://github.com/ramonsmits/docs.particular.net/tree/azure-storage-persistence-subscription-compatibility/samples/azure/storage-persistence

Please check this project and its 5 and 6 projects. It is very easy to subscribe/unsubscribe and check what is happening.

**Comment by SeanFeldman** [comment]
@ramonsmits we should probably convert the sample for NServiceBus v6 project in the docs to use ASQ transport rather than use Learning transport. And then verify on that repo, not the personal one 🙂

**Comment by SeanFeldman** [comment]
I've done the following:

1. Cloned the doco repo.
1. Upgraded both solutions ASP_1 and Azure_6 to ASQ transport (Client and Server endpoints).
1. Configured ASQ to use the local emulator.
1. Executed Azure_6 with pub/sub running.
1. Executed ASP_1 with pub/sub running.

Subscriptions table contained a single subscription record as expected with the value
`Samples.Azure.StoragePersistence.Client@UseDevelopmentStorage=true`.

@ramonsmits if you can a poke a whole in what I've done, let me know. Otherwise I don't know how to repro your issue.

I'm going to send a PR to remove Learning transport from this sample - it shouldn't be there as it hides pub/sub with Storage persistence.

**Comment by SeanFeldman** [comment]
Doco was updated. The sample for Azure Storage Persistence can be used as a test scenario w/o the need to clone the repo and change it.

@ramonsmits if you can capture the steps to repro this issue and those are difference from [what I've done](https://github.com/Particular/NServiceBus.Persistence.AzureStorage/issues/154#issuecomment-319528230), please reopen the issue with the steps. In case steps are identical, let's pair and review. Thank you.
