### ISSUE TITLE
DataBus-like property for Saga

### ISSUE THREAD

**Issue by janpieterz** [Particular/NServiceBus.Persistence.AzureStorage#159]
When working around https://github.com/Particular/NServiceBus.AzureServiceBus/issues/596 I looked into using the DataBus. For the current flow this isn't needed, as the batching as of now is setup to handle ~500,000 notifications in one batch (more than that the message size becomes too big for the standard ASB).

While doing that, the need to move away from the Saga was the storage capabilities, but what ended up happening is that we now have some 'home grown' saga that simply uses a table to store a row per record in the 'list to notify'.

It'd be great if, just like sending big messages, a Saga could be instructed, when running on Azure Storage, to store part of it's data as a Blob. 

Might just be too big a feature for too small a target, but at least thought it worth mentioning.

**Comment by SeanFeldman** [comment]
@janpieterz Saga should be really a coordinator and not perform any work by itself. Storing state should be solely be done for the decisions saga needs to take, not the actual work. I'd argue that storing notifications and executing those is not what saga [should be doing](https://docs.particular.net/nservicebus/sagas/#accessing-databases-and-other-resources-from-a-saga).
