### ISSUE TITLE
Make setting for secondary indices existence mandatory

### ISSUE THREAD

**Issue by boblangley** [Particular/NServiceBus.Persistence.AzureStorage#162]
### PoA

- [ ] Make the setting mandatory - **PR** #165
- [ ] Add to the upgrade guide
- [ ] Update doco/samples

### Original discussion

See #130 

We added the configuration option for users to tell the persistence to assume secondary indices exist, skipping a full table scan when creating new sagas. I think that at some point we should swap the behavior so this is the default, but older customers that may have old sagas without a secondary index record have an option to revert to the old behavior for a time.

We are about to release a new major. Is this the time?

**Comment by SeanFeldman** [comment]
That would be a breaking change, so major is a good candidate, indeed.

> older customers that may have old sagas without a secondary index record have an option to revert to the old behavior for a time.

We've introduced this in 1.4 to allow those that are on 1.0 to opt out from full scans because their data is already in proper state (i.e. secondary indicies exist). So I think whoever is upgrading, is safe since the upgrade path from 6.x would be 1.x first, and then 2.0.

@Particular/azure-maintainers am I correct about my assumptions?

**Comment by yvesgoeleven** [comment]
I'd say leave as is for a while, the longer we leave as is, the more chance that data is migrated

**Comment by boblangley** [comment]
Perhaps make the behavior choice explicit in this release?

**Comment by SeanFeldman** [comment]
That is a different then. Don't see a problem with that, other than customers will have to provide the value (additional mandatory setting). In a way, it will generate awareness.

**Comment by danielmarbach** [comment]
@boblangley @SeanFeldman I'm for making this a mandatory choice. We can then remove the mandatory choice in the next major.

**Comment by yvesgoeleven** [comment]
good suggestion, make it a mandatory choice

**Comment by SeanFeldman** [comment]
During maintainers sync we've concluded that forcing a mandatory setting is still not going to resolve this issue. Once I'll raise a PlatDev issue, will close this one. The setting will remain unchanged for v2 of the persistence.
