### ISSUE TITLE
Provide opt-in capability to store oversized messages in a blob 

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus.Persistence.AzureStorage#17]
so that the message doesn't get lost

**Comment by yvesgoeleven** [comment]
See https://github.com/Particular/NServiceBus.AzureServiceBus/issues/57

**Comment by udidahan** [comment]
This should be connected to one of the data bus issues.

**Comment by yvesgoeleven** [comment]
@udidahan you mean we should mention usage of databus feature in this exceptions error message? That's something we can do, but we cannot magically turn an oversized message into a databus message.

**Comment by udidahan** [comment]
I'm saying that we have other issues that talk about improvements to the databus and this should be connected to them.

**Comment by Scooletz** [comment]
Is this a storage concern @yvesgoeleven ?

**Comment by yvesgoeleven** [comment]
@Scooletz I'd say we can close this, we now have a documentation section that describes how one would implement this, http://docs.particular.net/nservicebus/azure-service-bus/oversized-sends. There is probably no need to have this ootb as it is of limited applicability and a dependency mess (both ASB & storage dependency).
