### ISSUE TITLE
Subscriptions include message assembly version

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.Persistence.AzureStorage#173]
When ASP stores a subscription, it also stores version of the assembly containing the message.

```
Shared.OrderCompleted, Version=1.0.0.0
```

This is a source of issues when messages assembly gets versioned and requires a new subscription to be create.

Other transports such as ASB or RabbitMQ ignore assembly version.

**Comment by SeanFeldman** [comment]
@Particular/azure-maintainers to fix this, we'd need to introduce a breaking change that would only be possible in a major release. Do we want to include this in v8?

**Comment by yvesgoeleven** [comment]
Can't we do this in a backward compat way? Do the assembly lookup on part of the string?

**Comment by SeanFeldman** [comment]
@boblangley and myself have discussed this. Here's the summary:

- Today, if message assembly is versioned, there's a need in system down time to perform safe message assembly upgrade.
- If we decide to drop assembly version from the PartitionKey
    - For customers that **do** version their assemblies, the deployment would be no different from the described above.
    - For customers that **do not** version their assemblies, it would required system down time for no good reason.

Decision is to hold off on this. Most (if not all) customers do not version their message assembly. Those that do, go through the rigorous  upgrade process described in the list. Additionally, there might be potentially two other initiatives that will touch this issue - [ASQ native pub/sub](https://github.com/Particular/NServiceBus.AzureStorageQueues/issues/277) and future support for CosmosDB Table API as persistence.
