### ISSUE TITLE
Update Storage library to the latest (9.x)

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.Persistence.AzureStorage#197]
We're one major and half a year behind

**Comment by sjbench** [comment]
Is there a timeline for this item?

**Comment by SeanFeldman** [comment]
Hi @sjbench,
Is this a blocking issue for what you're doing? Thank you.

**Comment by sjbench** [comment]
@SeanFeldman yes it is as we already use Azure Storage for another function and the versions are in conflict.

**Comment by SeanFeldman** [comment]
It's out https://discuss.particular.net/t/nservicebus-azure-transports-windowsazurestoragequeues-8-1-0-minor-release-available/786 🎉 
Thank you for your patience.

**Comment by sjbench** [comment]
So there are updates to the Transports but not Persistence yet?  Or am I missing something?

**Comment by yvesgoeleven** [comment]
@sjbench that will follow later today
