### ISSUE TITLE
Add support for Managed Service Identity (MSI)

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.Persistence.AzureStorage#223]
_Related to https://github.com/Particular/NServiceBus.DataBus.AzureBlobStorage/issues/61_

Currently, Azure Persistence does not support Managed Service Identity (MSI) while both ASB and ASB Legacy support this.

**Comment by SeanFeldman** [comment]
This would require Storage Blob and CosmosDB Tables API packages

- https://www.nuget.org/packages/Microsoft.Azure.Storage.Blob/11.0.1
- https://www.nuget.org/packages/Microsoft.Azure.Cosmos.Table/1.0.5

which is not what this persistence is using https://github.com/Particular/NServiceBus.Persistence.AzureStorage/blob/fe22f182fb24aaf2e78967a5a731c1588449b4ef/src/NServiceBus.Persistence.AzureStorage/NServiceBus.Persistence.AzureStorage.csproj#L11

WindowsAzure.Storage is a deprecated package.

**Comment by kwaazaar** [comment]
Would be great if this could be supported.

**Comment by WilliamBZA** [comment]
This cannot be done within Azure Storage, as the underlying API does not support MI. This means it is impossible for us to add MI support without changing the storage to CosmosDB. Changing to Cosmos DB would be a different underlying storage mechanism, so would not be within this package anyway. So the takeaway is: there is nothing we can do to add MI to the Azure Storage Persistence package.

**Comment by kwaazaar** [comment]
@WilliamBZA Blobstorage does support MSI: https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/services-support-managed-identities#azure-storage-blobs-and-queues

**Comment by WilliamBZA** [comment]
Yes, Azure Storage supports MSI for Queues and Blobs, but not Tables which is what we need to add support to the NServiceBus.Persistence.AzureStorage package. 😞
