### ISSUE TITLE
Saga data serialization. Provide custom JsonSerializerSettings 

### ISSUE THREAD

**Issue by thecrockster** [Particular/NServiceBus.Persistence.AzureStorage#262]
I've noticed that both SqlPersistence and ServiceFabricPersistence allow custom JsonSerializerSettings but AzureStoragePersistence does not. Is this something worth considering?

```
var jsonSerializerSettings = new JsonSerializerSettings
{
    ContractResolver = new PrivateSetterAndCtorContractResolver()
};

var persistence = endpoint.UsePersistence<AzureStoragePersistence>().ConnectionString("UseDevelopmentStorage=true");
var sagaSettings = persistence.SagaSettings();
sagaSettings.JsonSettings(jsonSerializerSettings);
```

**Comment by SeanFeldman** [comment]
@thecrockster, thank you for the suggestion. Azure Storage Persistence serialized the types that would normally not be valid for Storage tables. Usually, this is not something customers would access. I am curious to hear what's the use case you have to control the serialization of the data internal to the persistence?

**Comment by thecrockster** [comment]
@SeanFeldman, Using Table Storage. We have a List inside our SagaData. The properties on the list have private setters. As we progress though the Saga workflow we update a boolean value in the list to true. However on each update the previously set boolean value reverts back to false. To resolve this we either make the setter public or use the [JsonProperty] attribute. However our preferred method for dealing with this would be via the JsonSerializerSettings and ContractResolver.

```
public class SendCommunicationSagaDataV2 : ContainSagaData
    {
        public SendCommunicationSagaDataV2()
        {
            this.SubBatches = new List<SubBatch>();
        }

        public Guid CommunicationGuid { get; set; }

        public List<SubBatch> SubBatches { get; set; }

        public void AddSubBatch(Guid subBatchId)
        {
            this.SubBatches.Add(new SubBatch(subBatchId));
        }

        public void MarkSubBatchSent(Guid subBatchId)
        {
            this.SubBatches.Single(s => s.SubBatchId == subBatchId).SentIsSent();
        }
    }

    public class SubBatch
    {
        public SubBatch(Guid subBatchId)
        {
            this.SubBatchId = subBatchId;
        }

        public Guid SubBatchId { get; private set; }

        public bool IsSent { get; private set; }

        public void SentIsSent()
        {
            this.IsSent = true;
        }
    }
```

**Comment by SeanFeldman** [comment]
Thank you, @thecrockster. Given you have a workaround, this won't be marked as a high priority, but we'll consider this as a feature request and work on it based on the priority it will get.

Thank you again for raising this request and elaborating on the use-case. Appreciated.

**Comment by danielmarbach** [comment]
@thecrockster we are about to release a significant overhaul of the persisted that focuses on bringing in Azure Cosmos Table API compliance, performance/throughput improvements as well as atomic transactions spawning outbox, sagas, and synchronized storage. Unfortunately, this feature request hasn't made the cut into the next release.
