### ISSUE TITLE
Specyfing an 'odd' PartitionKeyScope might cause message loss

### ISSUE THREAD

**Issue by WojcikMike** [Particular/NServiceBus.Persistence.AzureStorage#361]
## Problem Description
Currently, AzureStorage persistence allows for users to configure PartitionKeyScope for timeouts https://docs.particular.net/persistence/azure-table/configuration?version=asp_2#timeout-configuration 

The default value provided has the format 'yyyy-MM-dd-HH'. This format is to transform the Time of the timeout as PartitionKey. However, if the user selects a time format where year, month and day are in other order than above the persistence will not trigger most of the timeouts.

The problematic code is here: https://github.com/Particular/NServiceBus.Persistence.AzureStorage/blob/2.4.2/src/NServiceBus.Persistence.AzureStorage/Timeout/TimeoutLogic/TimeoutPersister.cs#L173-L181

The Partition key is a string and the comparison is based on the string value. Let us analyze an example.
There is a timeout for the date 2021-01-31 
Configured PartitionKeyScope is: dd-MM-yyyy
Today is 2021-02-01
Based on that the code that does comparison checks if

'31-01-2021' (timeout time after applying PartionKeyScope) < '01-02-2021' - that check return false as string comparison believes '31-... to be greater than '01-...

The nature of string comparison means that the only date format that would make the AzureStorage work is yyyy MM dd (in that order, the separation of segments is indifferent). Following the American date format of yyyy dd MM will already cause troubles with the persisted.

**Comment by SeanFeldman** [comment]
This is how the underlying technology works, it uses lexical comparison for sorting. From the [documentation](https://docs.microsoft.com/en-us/rest/api/storageservices/designing-a-scalable-partitioning-strategy-for-azure-table-storage#yyy):

> The clustered index sorts by the PartitionKey in ascending order and then by RowKey in ascending order. The sort order is observed in all query responses. Lexical comparisons are used during the sorting operation. A string value of "111" appears before a string value of "2". In some cases, you might want the sort order to be numeric. To sort in a numeric and ascending order, you must use fixed-length, zero-padded strings. In the preceding example, "002" appears before "111".

**Comment by danielmarbach** [comment]
This bug affects 2.4 of the persistence which is [out of support](https://docs.particular.net/nservicebus/upgrades/supported-versions#persistence-packages-nservicebus-persistence-azurestorage)

Closing the issue.
