### ISSUE TITLE
Supporting Subscriptions from v5 Core in v6

### ISSUE THREAD

**Issue by dbelcham** [Particular/NServiceBus.Persistence.AzureStorage#41]
Connects to https://github.com/Particular/PlatformDevelopment/issues/729

When converting the subscription code I noticed that we only persisted the transport address and the message type. Once upgraded to Core v6, ASP will need to store and retrieve both the transport address and the endpoint name. This is not a problem for subscriptions that are created after the new ASP assemblies are released, but it is a problem for the subscriptions that were created with Core v5 and retrieved using the Core v6 version of ASP.

A subscription created against the Core v5 assemblies will have no specific Endpoint Name to return when requested by the Core v6 assemblies. As such, we need to figure out how to construct that Endpoint Name from the data we have (transport address and message type).

In discussion with @seanfeldman we were looking at message type and that value, once decoded, looks like:

`Samples.Azure.StoragePersistence.Client@SOME-MACHINE`

We can parse the Endpoint Name from that value, but it raised the question of on-premise vs Azure hosted endpoints. On-premise endpoints will have a message type that includes the '@' symbol followed by the machine name. My understanding is that those hosted in Azure will not have the '@' and machine name in them.

The question we ended up on was to if having two endpoints registering as subscribers, each with an endpoint name that only consists of the type, would cause issues?

@yvesgoeleven @Scooletz @Particular/azure-maintainers

**Comment by SzymonPobiega** [comment]
Subscriber endpoint can be null and the core is prepared to handle such cases. No need to reverse-engineer the endpoint name.

**Comment by andreasohlund** [comment]
Based on the [comment ](https://github.com/Particular/NServiceBus.AzureStoragePersistence/issues/41#issuecomment-194706134)by @SzymonPobiega can we close this one?

**Comment by yvesgoeleven** [comment]
Needs validation /cc @WilliamBZA

**Comment by Scooletz** [comment]
@WilliamBZA What's the status of this?

**Comment by WilliamBZA** [comment]
No work unless prioritised by squad. So @Scooletz it's exactly where it was 18 days ago.

**Comment by Scooletz** [comment]
@WilliamBZA Just pinging :) Thx

**Comment by andreasohlund** [comment]
Is this a blocker for beta?

**Comment by Scooletz** [comment]
@andreasohlund We can't forbid endpoint by endpoint upgrade, hence we need to ensure that subscriptions created by v5 will be handled by v6 properly (during upgrade). Having that said, this should be considered as the beta preparation part.
I assume, that, if possible, @WilliamBZA could continue the validation when this becomes WIP.

**Comment by andreasohlund** [comment]
>We can't forbid endpoint by endpoint upgrade, hence we need to ensure that subscriptions created by v5 will be handled by v6 properly (during upgrade)

That would definitely block a RC, how likely are users to hit this?

**Comment by Scooletz** [comment]
@andreasohlund As far as I can see from the comments above, it's unlikely. Still we need to keep this to finish the check and ensure that it won't happen.

**Comment by WilliamBZA** [comment]
it _should_ work just fine. I just think it's simple enough that we _should_ verify before getting a support case for it.

**Comment by SzymonPobiega** [comment]
As I stated before, I don't think there is any work to be done here. All other persistence stores just return `null` when no endopoint is defined and the core expects that this value might be missing.

That being said, I understand that ASP persistence is usually coupled with ASQ transport. Here't the behavior of the core in such a scenario:
 * If no *discriminator* has been provided via `config.ScaleOut.InstanceDiscriminator`, there is a single queue shared by all scaled out instances so there is a single transport address all instances use for subscribing. Missing endpoint name does not cause problems
 * If there is *discriminator* set for each subscriber instance, these instances would (in V5) subscribe with their unique address. In V6 they will subscribe using the shared address. The difference is that in 5 each instance would get a copy of an event while in V6 each event will be set to a single instance. This problem has been already discussed here https://github.com/Particular/NServiceBus/issues/3495

**Comment by kbaley** [comment]
So who wants to say definitively that we should either close this or try smoke testing it?

**Comment by kbaley** [comment]
Does this sound like a suitable test?

- Create a V5 publisher with NServiceBus.Azure (configured for storage persistence)
- Create a V5 subscriber
- Start the endpoints and publish a message
- Upgrade V5 publisher to V6 and switch to NServiceBus.AzureStoragePersistence
- Start the endpoints and publish a message

Repeat the test with two V5 subscribers with different discriminators.

**Comment by WilliamBZA** [comment]
Definitely smoke-test.

To test the persistence we would need to use something that persists some info, a timout or saga would work here. So perhaps start a saga in a V5 endpoint, upgrade to V6 and attempt to continue the saga.

**Comment by SzymonPobiega** [comment]
Sounds like a good plan!

**Comment by kbaley** [comment]
@bording @SeanFeldman and I went through an upgrade scenario and discovered that ASP does indeed have a bug. ASP doesn't allow for an empty endpoint name and will throw an exception if it processes a subscription request from an earlier version. Watch for a PR coming soon!
