### ISSUE TITLE
missing re-throw in SecondaryIndexPersister?

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus.Persistence.AzureStorage#59]
this is in SecondaryIndexPersister. i assume a rethrow (outside the if) is missing?

                        try
                        {
                            await persist(deserializeSagaData).ConfigureAwait(false);
                        }
                        catch (StorageException e)
                        {
                            if (IsConflict(e))
                            {
                                // swallow ex as another worker created the primary under this key
                            }
                        }

**Comment by Scooletz** [comment]
I'm looking at this.
