### ISSUE TITLE
Generic handling of unsupported datatypes

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus.Persistence.AzureStorage#7]
From a suggestion on the google groups:

https://groups.google.com/forum/#!topic/particularsoftware/gBAanbup0Bo

To add logic to the saga persister that unsupported datatypes would be json serialized and stored, instead of throwing a runtime error.

**Comment by Scooletz** [comment]
@yvesgoeleven How would you store information about the type of the property? As a type's full name or sth else? What about collecitions that are not that easy to decode, for instance `List<Guid>` generates mouthful: 
>System.Collections.Generic.List`1[[System.Guid, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]

If we get this solved, this won't be a breaking change. Sagas that didn't work before (presumably exposed during tests) will work now. It looks like a happy path :)

**Comment by yvesgoeleven** [comment]
@Scooletz I would not store the data type, just de/serialize it into whatever the app has specified

**Comment by Scooletz** [comment]
Cool. This looks like a low handing fruit which can be dealt with under the maintainer budget.

**Comment by SeanFeldman** [comment]
According to PR #99 this should be in `release-1.0.0`, but it's not there [nor documented](https://docs.particular.net/nservicebus/azure-storage-persistence/#supported-saga-properties-types) as something that is available. Anyone searching for this functionality [gets confused](https://github.com/Particular/docs.particular.net/pull/2143#discussion_r97485036). Updating (or re-opening this issue with a comment) could help.

**Comment by adamralph** [comment]
There is also this: https://groups.google.com/forum/#!topic/particularsoftware/46g71TcjdXM

**Comment by SeanFeldman** [comment]
@adamralph I've updated the [general description](https://github.com/Particular/NServiceBus.Persistence.AzureStorage/issues/7#issue-84507414) with this reference earlier 😜
