### ISSUE TITLE
Completed saga does not remove secondary index record

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.Persistence.AzureStorage#74]
Connects to https://github.com/Particular/PlatformDevelopment/issues/836

## Who's affected

* Any user using NServiceBus.Azure persistence for sagas

## Symptoms

When saga completes, secondary index record is left behind, filling up storage table with records.

## Steps to reproduce

Start and complete a saga. Once saga completed, inspect storage table to find secondary index record. [Persistence sample](http://docs.particular.net/samples/azure/storage-persistence/) can be used to reproduce the issue.

**Comment by SeanFeldman** [comment]
[`Complete` operation](https://github.com/Particular/NServiceBus.Persistence.AzureStorage/blob/cc1cc995b7e4f10d6bdaa4e38afd89ca1754b31b/src/NServiceBus.Persistence.AzureStorage/SagaPersisters/AzureSagaPersister.cs#L88) doesn't remove the secondary index.

**Comment by Scooletz** [comment]
I've reviewed the code and you're right. It has the described bug. Should we wait till RC or use maintainers budget for it? Thoughts @Particular/azure-storage-persistence-maintainers ?

**Comment by dbelcham** [comment]
@Scooletz when you get to working on this can you make sure that there is a test that verifies the successful removal of the secondary index record?

**Comment by SeanFeldman** [comment]
With the fix, we should provide guidance / option to remove orphaned secondary indexes.

**Comment by Scooletz** [comment]
Sure. I will @dbelcham

**Comment by Scooletz** [comment]
Solved by #75
