### ISSUE TITLE
Flaky When_removing_timeouts_from_the_storage test

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus.Persistence.AzureStorage#83]
`When_removing_timeouts_from_the_storage` seems to be flaky. 

e.g. fails on this build: https://builds.particular.net/viewLog.html?buildId=168165&tab=buildResultsDiv&buildTypeId=NServiceBus_Persistence_NServiceBus_AzureStoragePersistence_Build
but is succeeds if run again: https://builds.particular.net/viewLog.html?buildId=168174&tab=buildResultsDiv&buildTypeId=NServiceBus_Persistence_NServiceBus_AzureStoragePersistence_Build

**Comment by Scooletz** [comment]
I've reviewed the test with Tim. I've had some doubts about assertion over tasks results rather than the awaited result, but this was a wrong assumption.
I've got doubts about running the removal tasks concurrently when removing a timeout though:
```
var timeoutDataTable = client.GetTableReference(timeoutDataTableName);

var timeoutDataEntity = await GetTimeoutData(timeoutDataTable, timeoutId, string.Empty).ConfigureAwait(false);
if (timeoutDataEntity == null)
{
    return false;
}

var deleteTasks = new List<Task>
{
    DeleteSagaEntity(timeoutId, timeoutDataTable, timeoutDataEntity),
    DeleteTimeEntity(timeoutDataTable, timeoutDataEntity.Time.ToString(partitionKeyScope), timeoutId),
    DeleteState(timeoutDataEntity.StateAddress)
};

try
{
    await Task.WhenAll(deleteTasks).ConfigureAwait(false);
    await DeleteMainEntity(timeoutDataEntity, timeoutDataTable).ConfigureAwait(false);
}
catch (StorageException e)
{
    if (e.RequestInformation.HttpStatusCode != (int)HttpStatusCode.NotFound)
    {
        throw;
    }

    return false;
}
```

Because deleteTasks are run in parallel, the timing might be different and they can be executed in an exotic order 1, 2, 3 for one remover and 2, 1, 3 for another. This could result in getting `NotFound` in each of them and failing a test. Having that said, should the approach for removing be revisited?

**Comment by timbussmann** [comment]
> can be executed in an exotic order 1, 2, 3 for one remover and 2, 1, 3 for another. This could result in getting NotFound in each of them and failing a test.

would that mean that none of the parallel tasks then manages to call `DeleteMainEntity` because of the exception?

**Comment by Scooletz** [comment]
As far as I see it, that could be a scenario. By `1, 2, 3` I was referring to:

1. DeleteSagaEntity
2. DeleteTimeEntity
3. DeleteState

So your statement @timbussmann would be a result of one of these above failing in two concurrent removals.

**Comment by timbussmann** [comment]
sounds like a bug we need to fix before the v6 RC then? @Particular/azure-storage-persistence-maintainers

**Comment by Scooletz** [comment]
It sounds like one. Let me try to repro that. I'll report my findings.
