### ISSUE TITLE
Consider introducing NSB generate correlation id for azure operations

### ISSUE THREAD

**Issue by Scooletz** [Particular/NServiceBus.Persistence.AzureStorage#88]
Currently, all the Azure Storage operations use the calls without providing an `OperationContext` instance. Passing a custom instance with `OperationContext.ClientRequestID` set to a value that has a common prefix for all the Azure operations in a given call could be helpful in:
- determining the cause of different problems
- reasoning about order of operations (just use `OperationContext.GlobalRequestCompleted` and print the id to a log or a test output)
- when needed, ensuring an order between operations run in parallel with `Task.WhenAll` (again using the global hook `OperationContext.GlobalRequestCompleted` + wait handles).

The PR showing a proposed solution is #89

**Comment by Scooletz** [comment]
@Particular/azure-storage-persistence-maintainers @Particular/azure-storage-queues-maintainers 
Maybe this should be brought not only for the persistence but also for transports as well? Especially now, when we have `ContextBag` being passed to `IStatePersister` as well as the transport seam, we could correlate sagas operations and transport operations together, to enable even better diagnostics when needed.

Thoughts?

**Comment by SeanFeldman** [comment]
> Maybe this should be brought not only for the persistence but also for transports as well?

ASQ could use it, but not ASB as it's not traceable as with storage operations.

**Comment by Scooletz** [comment]
Closing as #89 was closed.
