### ISSUE TITLE
Reconsider choice of copying some of ATT test to the AcceptanceTests of the project

### ISSUE THREAD

**Issue by Scooletz** [Particular/NServiceBus.Persistence.AzureStorage#95]
After dealing with multiple errors during bump up of the recent core6 beta7, I think, that we should reconsider the fact of copying acceptance tests to the storage solution. Should we use ATT project as a whole suite? I'm not sure, but using a copied set of tests (without applying fixes and changes from the core) doesn't look like a good idea. What's your opinion @Particular/azure-storage-persistence-maintainers ?

**Comment by SeanFeldman** [comment]
@Scooletz I recall a discussion about having a designated persistence acceptance tests package. Similar what today transports have for transports (NServiceBus.TransportTests). Is that something that should be discussed as a broader option for all persistences? By having a package like that, we'd also help the OSS community that create alternative implementation to have an idea if their code adheres to the expectations or not.

**Comment by Scooletz** [comment]
Yes, there's a will to provide a similar set of the persistence seam tests. Having this said (and reminding myself about it), I think that we can park this effort till the seam tests are provided. The only thing would be to extract `Azure Storage` related tests and maintain them on their own, without using the acceptance test framework.

**Comment by SeanFeldman** [comment]
We should look into this again. While working with @boblangley on #118 we couldn't find a test that would verify the behavior. Since the behavior is standard across all the persistences, having a shared test package would help.

**Comment by danielmarbach** [comment]
For the Service Fabric persistence, we came up with some standard tests that could be used. Though I think we should not tackle this as part of the maintainer work but look at it from a platform development standpoint. Probably all persisters have this problem right now. Let's close this in favour of https://github.com/Particular/PlatformDevelopment/issues/1525
